package(default_visibility = ["//src:__subpackages__"])

java_library(
    name = "auto",
    srcs = glob(["*.java"]),
    deps = [
        "//third_party:junit4",
    ],
)

filegroup(
    name = "srcs",
    srcs = glob(["**"]),
)
